/* eslint-disable import/prefer-default-export */
export const mockApplicationForm = {
  coverage: 'worker-compensation',
  steps: [
    {
      name: 'contact-info',
      label: 'Who is the primary contact for this policy?',
      hint:
        'This person will receive all communications from Newfront about this policy. You can change this contact information later. If you’re not sure, just add your contact information.',
      order: 0,
      questions: [
        {
          id: (Math.random() * 1000).toFixed(0),
          order: 0,
          name: 'name',
          label: 'Full name',
          type: 'text',
          isRequired: true,
        },
        {
          id: (Math.random() * 1000).toFixed(0),
          order: 1,
          name: 'role',
          label: 'Role',
          type: 'text',
          isRequired: false,
        },
        {
          id: (Math.random() * 1000).toFixed(0),
          order: 1,
          name: 'phone',
          label: 'Phone number',
          type: 'phone',
          isRequired: true,
        },
      ],
    },
    {
      name: 'company-info',
      label: 'Tell us about your company',
      order: 1,
      questions: [
        {
          id: (Math.random() * 1000).toFixed(0),
          order: 0,
          name: 'companyName',
          label: 'Company Name',
          type: 'text',
          isRequired: true,
        },
        {
          id: (Math.random() * 1000).toFixed(0),
          order: 1,
          name: 'fein',
          label: 'What is your Federal Employer Identification Number? (FEIN)',
          type: 'text',
          isRequired: true,
        },
        {
          id: (Math.random() * 1000).toFixed(0),
          order: 2,
          name: 'years',
          label: 'Years in business',
          type: 'number',
          isRequired: false,
        },
        {
          id: (Math.random() * 1000).toFixed(0),
          order: 3,
          name: 'locations',
          label: 'Number of locations',
          type: 'number',
          isRequired: false,
        },
        {
          id: (Math.random() * 1000).toFixed(0),
          order: 4,
          name: 'statesOperate',
          label: 'In which states do you operate?',
          type: 'text',
          isRequired: false,
        },
      ],
    },
    {
      name: 'employees-info',
      label: 'Tell us about your employees',
      order: 2,
      questions: [
        {
          id: (Math.random() * 1000).toFixed(0),
          order: 0,
          name: 'clinicName',
          label: 'What’s the name of the clinic, physician, or ER used for work injuries?',
          type: 'text',
          isRequired: false,
        },
        {
          id: (Math.random() * 1000).toFixed(0),
          order: 1,
          name: 'medicalInsurance',
          label: 'Do you provide group medical insurance?',
          type: 'checkbox',
          options: [true],
          isRequired: false,
        },
        {
          id: (Math.random() * 1000).toFixed(0),
          order: 2,
          name: 'retirementPlan',
          label: 'Do you offer a retirement or pension plan?',
          type: 'checkbox',
          options: [true],
          isRequired: false,
        },
        {
          id: (Math.random() * 1000).toFixed(0),
          order: 3,
          name: 'paidVacation',
          label: 'Do you give paid vacation?',
          type: 'checkbox',
          options: [true],
          isRequired: false,
        },
        {
          id: (Math.random() * 1000).toFixed(0),
          order: 4,
          name: 'paidVacationDetails',
          label: 'Please provide details about the paid vacation',
          type: 'text',
          dependsOn: 'paidVacation',
          dependsOnOption: true,
          isRequired: true,
        },
      ],
    },
    {
      name: 'payment-info',
      label: 'How do you want to pay for your policy?',
      order: 3,
      questions: [
        {
          id: (Math.random() * 1000).toFixed(0),
          order: 0,
          name: 'policyPayment',
          label: 'What’s the name of the clinic, physician, or ER used for work injuries?',
          type: 'radio',
          isRequired: false,
          options: [
            {
              name: 'I want to pay Newfront',
              value: 'newfront',
              hint: 'You’ll pay Newfront instead of paying each insurance company separately. There are no fees.',
            },
            {
              name: 'I want to pay the insurance company directly',
              value: 'company',
              hint:
                'You’ll receive bills from the insurance company and it will be your responsibility to make sure they are paid to keep your coverage.',
            },
          ],
        },
      ],
    },
  ],
};
